# Generated by Django 5.2.3 on 2025-06-30 21:36

import django.db.models.deletion
import ejerciciosPJC.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.CharField(default=ejerciciosPJC.models.genera_identificador, editable=False, max_length=6, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=30)),
                ('enunciado', models.CharField(max_length=255)),
                ('tareas', models.CharField(max_length=150)),
                ('pistas', models.CharField(max_length=150)),
                ('entrada', models.CharField(max_length=100)),
                ('salida', models.CharField(max_length=100)),
                ('definicion', models.CharField(blank=True, max_length=70, null=True)),
                ('uml', models.CharField(blank=True, max_length=80, null=True)),
                ('prueba', models.CharField(max_length=80)),
                ('lenguaje', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_usuario', models.TextField(blank=True, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejerciciosPJC.ejercicios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'ejercicio'), name='unique_usuario_ejercicio')],
            },
        ),
    ]
